# Use Ubuntu 24.04 (development version) as the base image
FROM ubuntu:devel

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    meson \
    ninja-build \
    g++-13 \
    gcc-13 \
    clang-tidy \
    cppcheck \
    valgrind \
    git \
    python3-pip \
    doxygen \
    graphviz \
    libgtest-dev \
    && rm -rf /var/lib/apt/lists/*

# Install pipx 
RUN apt-get update && apt-get install -y pipx 
RUN pipx ensurepath 

# Install conan
RUN pipx install conan==2.8.1

# Set GCC 13 as the default compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

# Build and install Google Test
RUN cd /usr/src/gtest && \
    cmake CMakeLists.txt && \
    make && \
    cp lib/*.a /usr/lib

WORKDIR /app

ENV CXXFLAGS="-std=c++20"

CMD ["/bin/bash"]
